### ISSUE TITLE
Cannot find module `scroll-into-view-if-needed`

### ISSUE THREAD

**Issue by davipon** [janosh/svelte-multiselect#98]
After upgrading to v5.0.5, this error popped up:
`Cannot find module 'scroll-into-view-if-needed' imported from 'pathToWorkspace/node_modules/.pnpm/svelte-multiselect@5.0.5/node_modules/svelte-multiselect/MultiSelect.svelte'`

Not sure if this only happens in pnpm. I need to install `scroll-into-view-if-needed` manually to resolve it.

**Comment by janosh** [comment]
Oh interesting, I had assumed vite deps inlining would bundle the code from `scroll-into-view-if-needed` (see fbf9d8e). Should probably have read the docs first. I'll pull v5.0.5 from NPM.
